version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: yoga_redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yoga_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yoga_app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Замените на ваши данные существующей БД
      SPRING_DATASOURCE_URL: jdbc:postgresql://your-existing-db-host:5432/yoga_app
      SPRING_DATASOURCE_USERNAME: your_db_user
      SPRING_DATASOURCE_PASSWORD: your_db_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "18080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - yoga_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:

networks:
  yoga_network:
    driver: bridge
