version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: yoga_postgres
    environment:
      POSTGRES_DB: yoga_app
      POSTGRES_USER: yoga_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yoga_secure_password_123}
    ports:
      - "15432:5432"
    volumes:
      - yoga_postgres_data:/var/lib/postgresql/data
    networks:
      - yoga_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yoga_user -d yoga_app"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Memory limits
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis:
    image: redis:7-alpine
    container_name: yoga_redis
    ports:
      - "16379:6379"
    volumes:
      - yoga_redis_data:/data
    networks:
      - yoga_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Memory limits
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yoga_app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yoga_app
      SPRING_DATASOURCE_USERNAME: yoga_user
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-yoga_secure_password_123}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      # JVM memory settings
      JAVA_OPTS: "-Xmx128m -Xms64m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
    ports:
      - "18080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - yoga_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    # Memory limits
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 128M

volumes:
  yoga_postgres_data:
  yoga_redis_data:

networks:
  yoga_network:
    driver: bridge
